### ISSUE TITLE
[Feature]: integrate Claude AI to this project

### ISSUE THREAD

**Issue by Shivoo29** [akshat-OwO/syllabusx-client#114]
### What feature do you want?

So basically, I have Claude pro and I wanted its Api to get used while searching things so if you also think these features are necessary then you can assign this task to me, I can integrate it...

**Comment by akshat-OwO** [comment]
what's the progress for this @Shivoo29 ?

**Comment by Shivoo29** [comment]
actually i'll able to do this after 21st of December because my end semister exam are about to start @akshat-OwO  .

**Comment by akshat-OwO** [comment]
no worries i make this open till then

**Comment by akshat-OwO** [comment]
#123
