### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by akshat-OwO** [akshat-OwO/syllabusx-client#25]

**Comment by 0xSaksham** [comment]
Is there any update on this? I can start the work/

**Comment by akshat-OwO** [comment]
no updates from @a-dtya. Feel free to start working on it :)

**Comment by 0xSaksham** [comment]
Hey, I have external papers, after that, I'll contribute to the same. Also if anyone is in MAIT, I would love to meet for a coffee chat.

**Comment by 0xSaksham** [comment]
@akshat-OwO also point me to some resources on how you want this to look like.

**Comment by akshat-OwO** [comment]
You can have a look in several open-source project readmes. But make sure it includes these:

- A project banner
- overview
- installation
- contributing guidelines
- contact information of project maintainers

you can take a look at [ipuranklist](https://github.com/ankushgarg1998/ipu-ranklist)

if you want help you can contact me on discord: theshinyapple

**Comment by akshat-OwO** [comment]
@0xSaksham you working on this issue?

**Comment by 0xSaksham** [comment]
Yes I know, You guys in MAIT?

**Comment by ShouryaPal** [comment]
No bro, We are from BVCOE.

**Comment by akshat-OwO** [comment]
@0xSaksham bro you done? what's the progress?

**Comment by yom4n** [comment]
@0xSaksham 
Few changes in the readme:

1. Use this image for the logo instead of the current one https://i.imgur.com/ZKts3W5.png

2. Put this link for "contribution guidelines" - https://opensource.guide/how-to-contribute/#how-to-submit-a-contribution

3. The contact links of all three of us are different, Email for Akshat, Linkedin for Shourya and Twitter for me. Make it uniform either LinkedIn for all or Email (LinkedIn preferably) .

4. Also the my Twitter profile link redirects to my LinkedIn page? Make sure to check your commits before creating a PR.

There are some basic errors too. You'll find them if your read through once.

**Comment by 0xSaksham** [comment]
@yom4n This was the draft. So I created a PR just to let you know.

I will go through with the changes and submit another PR.

**Comment by yom4n** [comment]
Oh okay, makes sense now. Good luck 👍.

**Comment by 0xSaksham** [comment]
I'll push changes today or tomorrow.

Also I feel like after port to Next.js the site has become slow. It looks really good for sure.

**Comment by akshat-OwO** [comment]
You meant slow in developer build or in production?

**Comment by vaibhavx42** [comment]
Hey ,
Do you still need help with this?

**Comment by yom4n** [comment]
@vaibhavx42 Yes, we do. Pointers are mentioned in the previous comments you can start your work according to them.

**Comment by vaibhavx42** [comment]
hey @yom4n I'm done with those mentioned pointers, does the project require conventional PR /issues templates if yes I'll add them before submitting the PR.

**Comment by vaibhavx42** [comment]
Hey @akshat-OwO changes have been made .
> (optional) add a contributor's section and add your profile in it :)

For now I've added my profile as the contributors.  using [contrib.rocks](https://contrib.rocks/) might be a better approach as the contributor list grows. 

> Do suggest if we should make this repo hacktoberfest compatible and merge your PR using hacktoberfest tag.

This sounds like a great idea. Please go ahead and add the "hacktoberfest accepted" tag. I'm happy to have my contribution counted as one of my Hacktoberfest PRs. Thanks for considering it!

**Comment by akshat-OwO** [comment]
solved in #48
