### ISSUE TITLE
Implement Routing for SyllabusX

### ISSUE THREAD

**Issue by ShouryaPal** [akshat-OwO/syllabusx-client#32]
> This issue aims to implement routing using `react-router` or `tanstack/react-router` to allow users to directly access the syllabus of their subject  without going through the homepage.

- Currently users have to interact with slow homepage access the syllabus of their subject.
- Both libraries provide modern and scalable routing for React applications. It is upto you what suits you best.

**Comment by akshat-OwO** [comment]
done in V3
