### ISSUE TITLE
Last section namely, 'Practical Files' not readable and not getting scrolled down.

### ISSUE THREAD

**Issue by PrathamSikka24** [akshat-OwO/syllabusx-client#44]
![Screenshot (161)](https://github.com/akshat-OwO/syllabusx-client/assets/116445216/27408273-8c01-426d-856e-55822e20a007)
Steps to reproduce this issue:
Go to the syllabusx.live website, select your semester and stream. According to my requirement, I have selected ECE, 3rd semester. After selecting any particular subject, we get resources divided section-wise like theory, notes, practical, pyq, of which practical files is the last section. But it cannot be read, also it is not getting scrolled down so somebody may miss that the website provides practical files also. 
If I have to see it, I have to hide my task bar or hover upon it, but the UX will be much better if this is clarified.

**Comment by akshat-OwO** [comment]
I can see magnifying icon in your address bar. Seems you are zoomed in. Try to zoom out and see if the issue still exists

**Comment by PrathamSikka24** [comment]
Yes, it was my fault. I was 110% zoomed in. I will delete the issue,
somehow I unknowingly set 110% as default so every page opens that way.
Thank you Akshat.
