### ISSUE TITLE
Implement UI of Homepage

### ISSUE THREAD

**Issue by Krish-Panchani** [akshat-OwO/syllabusx-client#49]
![image](https://github.com/akshat-OwO/syllabusx-client/assets/74005086/dff43379-5a00-48d0-9c8f-e71a87e70f4b)

I can see on Homepage, All element are not centered.
Also set the Feedback & contribution button at bottom side.

**Comment by akshat-OwO** [comment]
Okay those buttons can be aligned with the rest of the buttons

**Comment by Krish-Panchani** [comment]
Ass

> Okay those buttons can be aligned with the rest of the buttons

Assign me

**Comment by akshat-OwO** [comment]
@Krish-Panchani someone has already made a PR on it. You can try to implement your way or correct their implementation
