### ISSUE TITLE
Adding light mode to the UI

### ISSUE THREAD

**Issue by SaRTHaK0909k** [akshat-OwO/syllabusx-client#50]
please assign me this issue under the tag hactoberfest 2k23 :)

**Comment by yom4n** [comment]
Alright, go ahead.

**Comment by akshat-OwO** [comment]
@SaRTHaK0909k you working on this?

**Comment by SaRTHaK0909k** [comment]
@akshat-OwO You can remove me from this issue because there has been a emergency on my side . I am sorry for not contributing , hope you dont mind.

**Comment by akshat-OwO** [comment]
Okay! No worries

**Comment by prerit2001** [comment]
Hi Assign this to me.

**Comment by akshat-OwO** [comment]
@prerit2001 go ahead!

**Comment by akshat-OwO** [comment]
@prerit2001 what's the progress?

**Comment by akshat-OwO** [comment]
No response from @prerit2001
