### ISSUE TITLE
Make scroll-area always visible

### ISSUE THREAD

**Issue by akshat-OwO** [akshat-OwO/syllabusx-client#53]
scroll-area in semester and branch button dropdowns should remain visible

you can read [Radix UI scroll-area primitive docs](https://www.radix-ui.com/primitives/docs/components/scroll-area) for reference

you'll need to change only one line I guess

**Comment by shreyanshig** [comment]
Hi @akshat-OwO, Could you please assign this issue to me?

**Comment by priyankeshh** [comment]
@akshat-OwO  can i work on this, I have worked on this already and shown you aswell

**Comment by akshat-OwO** [comment]
@shreyanshig you can start working on this issue

@priyankeshh let shreyansh try as he commented first

**Comment by akshat-OwO** [comment]
@shreyanshig you there?

**Comment by akshat-OwO** [comment]
@priyankeshh you can start working on this issue!

**Comment by akshat-OwO** [comment]
Yes!
