### ISSUE TITLE
Add Pull Request Template

### ISSUE THREAD

**Issue by SaarthakMaini** [akshat-OwO/syllabusx-client#54]
Pull request templates allow your organizations to have a default text when you create a pull request on GitHub.

They allow for collaboration between contributors and maintainers, offer an opportunity to communicate changes that have been made and why they are important, and the ability for maintainers to provide feedback.

Because contributors come from different backgrounds, have varying degrees of experience, and speak different languages, I think it would be a good idea to inculcate a Pull Request Template to the respository.

**Comment by SaarthakMaini** [comment]
If possible, may I work on this issue, under Hacktoberfest?

Thank you!

**Comment by akshat-OwO** [comment]
Sure! I have assigned you to work on this issue
