### ISSUE TITLE
Add Issue Template

### ISSUE THREAD

**Issue by SaarthakMaini** [akshat-OwO/syllabusx-client#56]
We can customize the templates that are available for contributors to use when they open new issues in your repository.

**Comment by SaarthakMaini** [comment]
If possible, may I work on this issue, under Hacktoberfest?

Thank you!

**Comment by akshat-OwO** [comment]
i think you did this already?

**Comment by SaarthakMaini** [comment]
I made a Pull Request template previously.

This issue is to add an "Issue Template"

`Pull Request Template` : Pull request templates allow your organizations to have a default text when you create a pull request on GitHub. It is quite useful to make sure to follow a standard process for every pull request and to have a to-do list for the author to check before requesting a review.

Used when creating Pull Requests

`Issue Template`: Issue Templates are issue submission templates you create for commonly addressed issues. They allow you to pre-define appropriate information and values for those issues, such as the Subject, Description, Issue Type, Subtype, Priority, Email Subscribers, Attachments, etc.

Used when creating issues.

Screenshot of Pull Request Template:

![image](https://github.com/akshat-OwO/syllabusx-client/assets/94912101/28239e1a-2d76-482a-9cc1-ba6a860ede74)

Screenshot of Issue Template :

![image](https://github.com/akshat-OwO/syllabusx-client/assets/94912101/e7da7942-62f2-463a-9fe2-e3b1f6b59f35)

**Comment by akshat-OwO** [comment]
@SaarthakMaini you can work on this. My bad, I got confused

**Comment by akshat-OwO** [comment]
@SaarthakMaini can you check issue template again I am not able to create an issue

**Comment by akshat-OwO** [comment]
nvm I fixed it
